apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: zpn8l9wuc-python 
  janus-idp.io/tekton: zpn8l9wuc-python
  backstage.io/kubernetes-id: zpn8l9wuc-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: zpn8l9wuc-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml