apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: zpn8l9wuc-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: zpn8l9wuc-python 
  name: zpn8l9wuc-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: zpn8l9wuc-python 
